<script setup>
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api, readSSE } from '../api'
const tab = ref('chat'), prompt = ref(''), busy = ref(false), chat = ref([{ role: 'assistant', content: '你好，我是 InnovationCore 平台助手。当前默认展示模拟回复，可通过后端环境变量接入真实 LLM。' }])
const papers = ref([]), query = ref(''), integrations = ref([]), selectedTool = ref('research'), toolText = ref(''), toolOutput = ref('')
const tools = [{ value: 'research', label: 'Deep Research' }, { value: 'ppt', label: 'PPT 生成' }, { value: 'prompt', label: 'Prompt 优化' }, { value: 'translate', label: '论文翻译' }, { value: 'download', label: '模型高速下载' }]
let controller
async function search() { papers.value = (await api.get('/agents/papers', { params: { q: query.value } })).rows }
onMounted(async () => { await search(); integrations.value = await api.get('/agents/integrations') })
onUnmounted(() => controller?.abort())
async function send() { const message = prompt.value.trim(); if (!message || busy.value) return; const history = chat.value.slice(-12).map(x => ({ role: x.role, content: x.content })); chat.value.push({ role: 'user', content: message }); const reply = reactive({ role: 'assistant', content: '' }); chat.value.push(reply); prompt.value = ''; busy.value = true; controller = new AbortController(); try { await readSSE('/agents/chat/stream', { message, history }, (event, data) => { if (event === 'chunk') reply.content += data.text; if (event === 'error') reply.content = `服务调用失败：${data.detail || data.message}` }, controller.signal) } catch (error) { reply.content = `请求失败：${error.message}` } finally { busy.value = false } }
async function runTool() { if (!toolText.value.trim()) return ElMessage.warning('请先输入内容'); const result = await api.post(`/agents/tools/${selectedTool.value}`, { content: toolText.value }); toolOutput.value = result.output }
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">AGENT / WORKSPACE</div><h1>Agent 工作台</h1><p class="subtitle">对话、论文发现与智能创作工具的统一入口。</p></div></div>
  <div class="notice">聊天默认模拟；论文目录和创作工具为可替换的打桩实现。外部服务未配置时不会抓取论文、生成文件或下载模型。</div>
  <el-tabs v-model="tab"><el-tab-pane label="智能对话" name="chat" /><el-tab-pane label="论文助手" name="papers" /><el-tab-pane label="创作工具" name="tools" /><el-tab-pane label="服务集成" name="integrations" /></el-tabs>
  <div v-if="tab === 'chat'" class="card chat-card"><div class="chat-top"><span class="signal" /> 创新平台助手 <span class="muted small">SSE 流式输出</span></div><div class="chat-messages"><div v-for="(item, i) in chat" :key="i" class="message" :class="item.role"><div class="message-avatar">{{ item.role === 'user' ? '我' : 'AI' }}</div><div class="message-text">{{ item.content || '正在生成…' }}</div></div></div><div class="chat-compose"><el-input v-model="prompt" type="textarea" :rows="3" placeholder="输入你的问题，例如：如何创建模型评测任务？" @keydown.ctrl.enter="send" /><div class="flex-between"><span class="muted small">Ctrl + Enter 发送</span><el-button type="primary" :loading="busy" @click="send">发送消息 →</el-button></div></div></div>
  <div v-if="tab === 'papers'" class="card card-pad"><div class="card-header"><h2>论文检索</h2><span class="chip">示例目录</span></div><div class="toolbar"><el-input v-model="query" placeholder="搜索标题、领域或摘要" clearable @keyup.enter="search" /><el-button type="primary" @click="search">搜索</el-button></div><div v-for="paper in papers" :key="paper.id" class="paper"><div class="flex-between"><h3>{{ paper.title }}</h3><span class="chip">{{ paper.category }}</span></div><p class="subtitle">{{ paper.abstract }}</p><div class="muted small">{{ paper.year }} · {{ paper.source }}</div></div><div v-if="!papers.length" class="empty">没有匹配的论文</div></div>
  <div v-if="tab === 'tools'" class="grid two"><section class="card card-pad"><div class="card-header"><h2>选择工具</h2><span class="chip">模拟适配器</span></div><el-select v-model="selectedTool" style="width:100%;margin-bottom:18px"><el-option v-for="item in tools" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-input v-model="toolText" type="textarea" :rows="7" placeholder="描述你的研究主题、演示目标、提示词或论文内容..." /><el-button type="primary" style="margin-top:18px" @click="runTool">运行工具</el-button></section><section class="card card-pad"><div class="card-header"><h2>执行结果</h2><span class="muted small">仅供流程演示</span></div><div v-if="toolOutput" class="tool-output">{{ toolOutput }}</div><div v-else class="empty">选择工具并提交内容后，在这里查看响应。</div></section></div>
  <div v-if="tab === 'integrations'" class="card card-pad"><div class="card-header"><h2>第三方服务</h2><span class="muted small">独立适配接口</span></div><div class="grid three"><div v-for="entry in integrations" :key="entry.name" class="integration"><span class="integration-icon">✧</span><strong>{{ entry.name }}</strong><el-tag size="small" type="info">{{ entry.status }}</el-tag></div></div></div>
</template>
<style scoped>
.chat-card { max-width: 970px; overflow: hidden; }.chat-top { border-bottom:1px solid #edf0f3; padding:16px 21px; font-weight:700; font-size:13px; }.chat-top .muted { float:right; font-weight:400; }.chat-messages { height:440px; overflow:auto; padding:25px; display:flex; flex-direction:column; gap:20px; background:#fdfdfe; }.message { display:flex; align-items:flex-start; gap:10px; max-width:83%; }.message.user { align-self:flex-end; flex-direction:row-reverse; }.message-avatar { display:grid; place-items:center; background:#293b56; color:#fff; border-radius:9px; width:29px; height:29px; flex:0 0 29px; font-size:11px; font-weight:700; }.message.user .message-avatar { background:#c91e32; }.message-text { background:#fff; border:1px solid #ecedf0; padding:12px 15px; border-radius:4px 12px 12px 12px; white-space:pre-wrap; line-height:1.7; font-size:13px; }.message.user .message-text { background:#fff1f2; border-color:#f8d9de; border-radius:12px 4px 12px 12px; }.chat-compose { padding:16px 21px; border-top:1px solid #edf0f3; }.chat-compose .flex-between { margin-top:11px; }.paper { padding:18px 0; border-top:1px solid #edf0f3; }.paper h3 { font-size:15px; margin:0 0 9px; }.paper p { margin-bottom:10px; }.tool-output { background:#f7f8fa; padding:20px; border-radius:8px; line-height:1.8; white-space:pre-wrap; font-size:13px; }.integration { border:1px solid #e9edf1; border-radius:9px; padding:20px; display:grid; gap:12px; justify-items:start; font-size:13px; }.integration-icon { font-size:25px; color:#c91e32; }
</style>
