<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../api'
import EChart from '../components/EChart.vue'
import VisibilityField from '../components/VisibilityField.vue'
import VisibilityTag from '../components/VisibilityTag.vue'
const tab = ref('annotation'), datasets = ref([]), rows = ref([]), governance = ref(null)
const form = reactive({ dataset_id: '', content: '', label: '', visibility: 'private' })
async function load() { [datasets.value, rows.value, governance.value] = await Promise.all([api.get('/datasets'), api.get('/annotations'), api.get('/data-governance')]); if (!form.dataset_id && datasets.value.length) form.dataset_id = datasets.value[0].id }
onMounted(load)
async function save() { if (!form.dataset_id || !form.content.trim() || !form.label.trim()) return ElMessage.warning('请填写数据集、标注内容和标签'); await api.post('/annotations', form); form.content = ''; form.label = ''; form.visibility = 'private'; await load(); ElMessage.success('标注记录已保存') }
const chart = computed(() => ({ tooltip: {}, grid: { left: 100, right: 25, top: 10, bottom: 25 }, xAxis: { type: 'value', splitLine: { lineStyle: { color: '#f0f1f4' } } }, yAxis: { type: 'category', data: Object.keys(governance.value?.categories || {}), axisLine: { lineStyle: { color: '#e7ebf0' } } }, series: [{ type: 'bar', barWidth: 20, data: Object.values(governance.value?.categories || {}), itemStyle: { color: '#c91e32', borderRadius: [0,4,4,0] } }] }))
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">DATA / GOVERNANCE</div><h1>数据标注与治理</h1><p class="subtitle">沉淀人工标注结果，查看数据资产和下载使用情况。</p></div></div>
  <el-tabs v-model="tab"><el-tab-pane label="在线标注" name="annotation" /><el-tab-pane label="治理总览" name="governance" /></el-tabs>
  <div v-if="tab === 'annotation'" class="grid two"><section class="card card-pad"><div class="card-header"><h2>新增标注</h2><span class="chip">人工记录</span></div><el-form label-position="top"><el-form-item label="数据集"><el-select v-model="form.dataset_id" style="width:100%"><el-option v-for="d in datasets" :key="d.id" :label="d.name" :value="d.id" /></el-select></el-form-item><el-form-item label="样本内容"><el-input v-model="form.content" type="textarea" :rows="7" maxlength="8000" show-word-limit placeholder="输入或粘贴要标注的内容" /></el-form-item><el-form-item label="标签"><el-input v-model="form.label" placeholder="例如：意图分类 / 正样本" maxlength="80" /></el-form-item><VisibilityField v-model="form.visibility" /><el-button type="primary" @click="save">保存标注</el-button></el-form></section><section class="card card-pad"><div class="card-header"><h2>最近标注</h2><span class="muted small">{{ rows.length }} 条</span></div><div v-if="!rows.length" class="empty">暂无标注记录</div><div v-for="row in rows.slice(0,10)" :key="row.id" class="annotation-row"><div class="flex-between"><strong>{{ row.dataset_name }}</strong><span class="chip">{{ row.label }}</span></div><p>{{ row.content }}</p><div class="annotation-meta"><small class="muted">{{ row.created_at }}</small><VisibilityTag :visibility="row.visibility" /></div></div></section></div>
  <div v-if="tab === 'governance'"><div class="notice">VLA 场景与应用统计等待连接现有 VLA Data Backend；此处不编造真实业务数量。</div><div class="grid four"><div v-for="[name,value] in [['数据集',datasets.length],['上传文件',governance?.files],['文件下载',governance?.downloads],['标注记录',governance?.annotations]]" :key="name" class="card stat"><div class="stat-label">{{ name }}</div><div class="stat-number">{{ value ?? '—' }}</div><div class="stat-note">平台当前记录</div></div></div><div class="grid two section-gap"><section class="card card-pad"><div class="card-header"><h2>数据集分类</h2></div><EChart :option="chart" height="280px" /></section><section class="card card-pad"><div class="card-header"><h2>VLA 数据总览</h2><span class="chip">{{ governance?.vla.status || '待接入' }}</span></div><div class="empty">接入 VLA 数据服务后，可按场景与应用维度查看轨迹数量、质检结果和资产分布。</div></section></div></div>
</template>
<style scoped>.annotation-row { padding:13px 0; border-bottom:1px solid #edf0f3; font-size:13px; }.annotation-row p { color:#667287; line-height:1.6; margin:8px 0; overflow-wrap:anywhere; }.annotation-meta { display:flex; align-items:center; justify-content:space-between; gap:8px; }</style>
