<script setup>
import { onMounted, onUnmounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api } from '../api'
const tab = ref('architecture'), jobs = ref([]), models = ref([]), selected = ref(null), inferResult = ref(null)
const training = reactive({ name: '', accelerator: 'NPU', script: 'print("Hello InnovationCore")' })
const inference = reactive({ model_id: '', prompt: '', zone: '黄区' })
let timer
async function load() { [jobs.value, models.value] = await Promise.all([api.get('/school/jobs'), api.get('/models')]); if (selected.value) selected.value = jobs.value.find(x => x.id === selected.value.id) || null; if (!inference.model_id && models.value.length) inference.model_id = models.value[0].id }
onMounted(() => { load(); timer = setInterval(load, 3000) })
onUnmounted(() => clearInterval(timer))
async function submitJob() { if (!training.name.trim() || !training.script.trim()) return ElMessage.warning('请填写任务名称和脚本'); const job = await api.post('/school/jobs', training); selected.value = job; await load(); ElMessage.success('演示任务已提交') }
async function infer() { if (!inference.prompt.trim()) return ElMessage.warning('请输入推理内容'); inferResult.value = await api.post('/school/infer', inference) }
const stages = [ ['输入层', 'Token Embedding', '文本转向量表示'], ['注意力层', 'Self-Attention / GQA', '建模上下文关系'], ['前馈网络', 'FFN / MoE', '特征变换与专家路由'], ['归一化', 'RMSNorm + Residual', '稳定训练和信息传递'], ['输出层', 'LM Head', '生成下一个 Token 概率'] ]
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">LEARN / AI SCHOOL</div><h1>AI School</h1><p class="subtitle">理解模型架构，体验训练提交与在线推理工作流。</p></div></div>
  <div class="notice">训练脚本只保存和模拟进度，后端不会执行用户代码；推理响应与资源调度也是演示结果。</div>
  <el-tabs v-model="tab"><el-tab-pane label="模型架构" name="architecture" /><el-tab-pane label="模型训练" name="training" /><el-tab-pane label="在线推理" name="inference" /></el-tabs>
  <div v-if="tab === 'architecture'" class="grid two"><section class="card card-pad"><div class="card-header"><h2>Transformer 结构拆解</h2><span class="chip">交互概览</span></div><div class="arch-flow"><div v-for="(stage,i) in stages" :key="stage[0]" class="arch-row"><span class="arch-index">{{ String(i+1).padStart(2,'0') }}</span><div><strong>{{ stage[1] }}</strong><small>{{ stage[0] }} · {{ stage[2] }}</small></div><span class="arch-arrow">↓</span></div></div></section><section class="card card-pad"><div class="card-header"><h2>学习路径</h2><span class="muted small">从原理到实践</span></div><ul class="flow-list"><li><span class="flow-index">1</span> 理解 Token、Embedding 与位置编码</li><li><span class="flow-index">2</span> 拆解注意力、GQA 和 KV Cache</li><li><span class="flow-index">3</span> 分析 FFN、MoE 和推理吞吐</li><li><span class="flow-index">4</span> 提交训练任务并观察日志</li><li><span class="flow-index">5</span> 在推理沙箱验证模型行为</li></ul></section></div>
  <div v-if="tab === 'training'" class="grid two"><section class="card card-pad"><div class="card-header"><h2>提交训练任务</h2><span class="chip">不执行脚本</span></div><el-form label-position="top"><el-form-item label="任务名称"><el-input v-model="training.name" placeholder="例如：RMSNorm 实训" /></el-form-item><el-form-item label="计算资源"><el-radio-group v-model="training.accelerator"><el-radio-button label="NPU" value="NPU" /><el-radio-button label="GPU" value="GPU" /></el-radio-group></el-form-item><el-form-item label="Python 脚本"><el-input v-model="training.script" type="textarea" :rows="10" class="mono" /></el-form-item><el-button type="primary" @click="submitJob">提交演示任务</el-button></el-form></section><section class="card card-pad"><div class="card-header"><h2>任务与日志</h2><span class="muted small">{{ jobs.length }} 个任务</span></div><div v-if="!jobs.length" class="empty">尚无训练任务</div><div v-for="job in jobs" :key="job.id" class="job-row" @click="selected=job"><div class="flex-between"><strong>{{ job.name }}</strong><el-tag size="small" :type="job.status === 'completed' ? 'success' : 'warning'">{{ job.status }}</el-tag></div><div class="muted small">{{ job.accelerator }} · {{ job.created_at }}</div><el-progress :percentage="job.progress" :stroke-width="5" style="margin-top:8px" /></div><div v-if="selected" class="section-gap"><div class="card-header"><h2>{{ selected.name }} / 日志</h2></div><div class="log-box">{{ selected.logs.join('\n') }}</div></div></section></div>
  <div v-if="tab === 'inference'" class="grid two"><section class="card card-pad"><div class="card-header"><h2>推理沙箱</h2><span class="chip">模拟推理</span></div><el-form label-position="top"><el-form-item label="模型"><el-select v-model="inference.model_id" style="width:100%"><el-option v-for="m in models" :key="m.id" :label="m.name" :value="m.id" /></el-select></el-form-item><el-form-item label="资源分区"><el-radio-group v-model="inference.zone"><el-radio-button label="黄区" value="黄区" /><el-radio-button label="绿区" value="绿区" /></el-radio-group></el-form-item><el-form-item label="输入"><el-input v-model="inference.prompt" type="textarea" :rows="7" placeholder="输入推理问题..." /></el-form-item><el-button type="primary" @click="infer">开始推理</el-button></el-form></section><section class="card card-pad"><div class="card-header"><h2>推理输出</h2><span class="muted small">结果视图</span></div><div v-if="inferResult" class="tool-output"><div class="muted small">{{ inferResult.model }} · {{ inferResult.zone }} · 输入 {{ inferResult.tokens }} 字符</div><p style="margin-top:20px">{{ inferResult.output }}</p></div><div v-else class="empty">选择模型并输入问题，查看沙箱响应。</div></section></div>
</template>
<style scoped>.arch-flow { display:grid; gap:9px; }.arch-row { display:flex; align-items:center; gap:15px; padding:15px; background:#f8f9fb; border:1px solid #eef0f3; border-radius:8px; }.arch-index { color:#c91e32; font-weight:800; font-size:12px; }.arch-row strong,.arch-row small { display:block; }.arch-row strong { font-size:13px; }.arch-row small { margin-top:4px; color:#919aa9; font-size:11px; }.arch-arrow { margin-left:auto; color:#b7c0cd; }.job-row { cursor:pointer; padding:12px 0; border-bottom:1px solid #edf0f3; font-size:13px; }.job-row:hover { color:#c91e32; }.job-row .muted { margin-top:5px; }.tool-output { background:#f7f8fa; padding:20px; border-radius:8px; line-height:1.7; }</style>
